---
include:
  - board: halcyon_dongle//zmk
    shield: halcyon_elora_dongle
    artifact-name: halcyon_elora_dongle
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    snippet: studio-rpc-usb-uart

  - board: halcyon_wireless//zmk
    shield: halcyon_elora_left mod_battery_coincell mod_display_epaper_forest
    artifact-name: halcyon_elora_left_cc_epaper
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: halcyon_wireless//zmk
    shield: halcyon_elora_right mod_battery_coincell
    artifact-name: halcyon_elora_right_cc
